### PR TITLE
Update us-senate.csv

### PR DESCRIPTION
**Pull request by EricPaulson**
You have Brian Schatz listed as "Brian Shcatz" in pretty much all of your data. I'm fixing it here, but you should check all of your data to correct this.

### CODE REVIEW

**Comment by manifestinteractive** [comment]
@EricPaulson actually, now that I think of it, we actually pull in this CSV file automatically from our Google Sheets.  Can you make sure you changes are reflected there as well?  The next import this tool will just wipe our your data changes if they are not also in that spreadsheet.

You should have just gotten an invite from me for edit permissions to that spreadsheet ( sent it to your GitHub email address )

**Comment by EricPaulson** [comment]
Thanks for the merge! I'll go ahead and update the spreadsheet now too. This is a great resource!

**Comment by manifestinteractive** [comment]
@EricPaulson The Spreadsheet should be up to date now as well.  But if you do change something, go ahead and set the background color of the cells you change to green, so I can easily see which rows cells you altered.  All other house / governor data should also be up to date as well.

**Comment by EricPaulson** [comment]
Sounds good, I'll do that.

**Pull request merged**
